STATUS_TRUE = True
STATUS_FALSE = False

STATUS_SUCCESS = "success"
STATUS_FAIL = "fail"
STATUS_ERROR = "error"

HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_400_BAD_REQUEST = 400
HTTP_401_UNAUTHORIZED = 401
HTTP_403_FORBIDDEN = 403
HTTP_404_NOT_FOUND = 404
HTTP_409_CONFLICT = 409
HTTP_422_UNPROCESSABLE_ENTITY = 422
HTTP_500_INTERNAL_SERVER_ERROR = 500

SUCCESS_STATUS_CODES = [HTTP_200_OK, HTTP_201_CREATED]

GENERAL_MESSAGES = {
    "VALIDATION_ERROR": "Validation failed.",
    "INTERNAL_ERROR": "Internal server error.",
}

COOKIE_SETTINGS = {
    "HTTPONLY": True,
    "SECURE": True,
    "SAMESITE": "Strict",
    "MAX_AGE": 3600,
}
