"""Add the tables

Revision ID: 88a79298c0fb
Revises: 001_add_dpdp_tables
Create Date: 2026-05-22 11:34:09.516531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88a79298c0fb'
down_revision: Union[str, None] = '001_add_dpdp_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dpdp_async_jobs', 'total',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('dpdp_async_jobs', 'processed',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('dpdp_async_jobs', 'failed',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_dpdp_async_jobs_form_id'), table_name='dpdp_async_jobs')
    op.drop_index(op.f('idx_dpdp_async_jobs_job_type'), table_name='dpdp_async_jobs')
    op.create_index('idx_dpdp_async_jobs_type', 'dpdp_async_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_dpdp_async_jobs_form_id'), 'dpdp_async_jobs', ['form_id'], unique=False)
    op.create_index(op.f('ix_dpdp_async_jobs_id'), 'dpdp_async_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_dpdp_async_jobs_job_type'), 'dpdp_async_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_dpdp_async_jobs_org_id'), 'dpdp_async_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_dpdp_async_jobs_status'), 'dpdp_async_jobs', ['status'], unique=False)
    op.drop_index(op.f('idx_dpdp_audit_log_actor_type'), table_name='dpdp_audit_log')
    op.drop_index(op.f('idx_dpdp_audit_log_target'), table_name='dpdp_audit_log')
    op.create_index(op.f('ix_dpdp_audit_log_action'), 'dpdp_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_dpdp_audit_log_actor'), 'dpdp_audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_dpdp_audit_log_actor_type'), 'dpdp_audit_log', ['actor_type'], unique=False)
    op.create_index(op.f('ix_dpdp_audit_log_id'), 'dpdp_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_dpdp_audit_log_org_id'), 'dpdp_audit_log', ['org_id'], unique=False)
    op.create_index(op.f('ix_dpdp_audit_log_target'), 'dpdp_audit_log', ['target'], unique=False)
    op.create_index(op.f('ix_dpdp_audit_log_ts'), 'dpdp_audit_log', ['ts'], unique=False)
    op.alter_column('dpdp_consent_forms', 'legal_basis',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('dpdp_consent_forms', 'retention_days',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('dpdp_consent_forms', 'expiry_days',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('idx_dpdp_consent_forms_code'), table_name='dpdp_consent_forms')
    op.create_index('idx_dpdp_consent_forms_code', 'dpdp_consent_forms', ['code'], unique=False)
    op.create_index(op.f('ix_dpdp_consent_forms_code'), 'dpdp_consent_forms', ['code'], unique=True)
    op.create_index(op.f('ix_dpdp_consent_forms_id'), 'dpdp_consent_forms', ['id'], unique=False)
    op.create_index(op.f('ix_dpdp_consent_forms_name'), 'dpdp_consent_forms', ['name'], unique=False)
    op.create_index(op.f('ix_dpdp_consent_forms_org_id'), 'dpdp_consent_forms', ['org_id'], unique=False)
    op.create_index(op.f('ix_dpdp_consent_forms_status'), 'dpdp_consent_forms', ['status'], unique=False)
    op.drop_index(op.f('idx_dpdp_consents_granted_at'), table_name='dpdp_consents')
    op.drop_index(op.f('idx_dpdp_consents_user_form'), table_name='dpdp_consents')
    op.create_index(op.f('ix_dpdp_consents_expires_at'), 'dpdp_consents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_dpdp_consents_form_id'), 'dpdp_consents', ['form_id'], unique=False)
    op.create_index(op.f('ix_dpdp_consents_id'), 'dpdp_consents', ['id'], unique=False)
    op.create_index(op.f('ix_dpdp_consents_status'), 'dpdp_consents', ['status'], unique=False)
    op.create_index(op.f('ix_dpdp_consents_user_id'), 'dpdp_consents', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_form_version', 'dpdp_consents', ['user_id', 'form_id', 'version'])
    op.alter_column('dpdp_form_versions', 'retention_days',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('dpdp_form_versions', 'expiry_days',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('uq_dpdp_form_versions_form_version'), table_name='dpdp_form_versions')
    op.create_index(op.f('ix_dpdp_form_versions_form_id'), 'dpdp_form_versions', ['form_id'], unique=False)
    op.create_index(op.f('ix_dpdp_form_versions_id'), 'dpdp_form_versions', ['id'], unique=False)
    op.create_index(op.f('ix_dpdp_form_versions_status'), 'dpdp_form_versions', ['status'], unique=False)
    op.create_unique_constraint('uq_form_id_version', 'dpdp_form_versions', ['form_id', 'version'])
    op.alter_column('dpdp_nominations', 'nominee_email_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('dpdp_nominations', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=1),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_dpdp_nominations_id'), 'dpdp_nominations', ['id'], unique=False)
    op.create_index(op.f('ix_dpdp_nominations_is_active'), 'dpdp_nominations', ['is_active'], unique=False)
    op.create_index(op.f('ix_dpdp_nominations_nominee_email_hash'), 'dpdp_nominations', ['nominee_email_hash'], unique=False)
    op.create_index(op.f('ix_dpdp_nominations_nominee_phone_hash'), 'dpdp_nominations', ['nominee_phone_hash'], unique=False)
    op.create_index(op.f('ix_dpdp_nominations_user_id'), 'dpdp_nominations', ['user_id'], unique=False)
    op.drop_index(op.f('idx_dpdp_orgs_dpdp_reg_id'), table_name='dpdp_orgs')
    op.drop_index(op.f('idx_dpdp_orgs_dpo_email_hash'), table_name='dpdp_orgs')
    op.drop_index(op.f('idx_dpdp_orgs_short_code'), table_name='dpdp_orgs')
    op.drop_index(op.f('idx_dpdp_orgs_name'), table_name='dpdp_orgs')
    op.create_index('idx_dpdp_orgs_name', 'dpdp_orgs', ['name'], unique=False)
    op.create_index(op.f('ix_dpdp_orgs_dpdp_reg_id'), 'dpdp_orgs', ['dpdp_reg_id'], unique=False)
    op.create_index(op.f('ix_dpdp_orgs_dpo_email_hash'), 'dpdp_orgs', ['dpo_email_hash'], unique=False)
    op.create_index(op.f('ix_dpdp_orgs_id'), 'dpdp_orgs', ['id'], unique=False)
    op.create_index(op.f('ix_dpdp_orgs_name'), 'dpdp_orgs', ['name'], unique=True)
    op.create_index(op.f('ix_dpdp_orgs_short_code'), 'dpdp_orgs', ['short_code'], unique=True)
    op.create_index(op.f('ix_dpdp_orgs_status'), 'dpdp_orgs', ['status'], unique=False)
    op.alter_column('dpdp_users', 'name',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('dpdp_users', 'name_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('dpdp_users', 'email',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('dpdp_users', 'email_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('dpdp_users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=1),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_dpdp_users_name_hash'), table_name='dpdp_users')
    op.drop_index(op.f('idx_dpdp_users_phone_hash'), table_name='dpdp_users')
    op.drop_index(op.f('idx_dpdp_users_email_hash'), table_name='dpdp_users')
    op.create_index('idx_dpdp_users_email_hash', 'dpdp_users', ['email_hash'], unique=False)
    op.create_index(op.f('ix_dpdp_users_email_hash'), 'dpdp_users', ['email_hash'], unique=True)
    op.create_index(op.f('ix_dpdp_users_id'), 'dpdp_users', ['id'], unique=False)
    op.create_index(op.f('ix_dpdp_users_is_active'), 'dpdp_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_dpdp_users_name_hash'), 'dpdp_users', ['name_hash'], unique=False)
    op.create_index(op.f('ix_dpdp_users_org_id'), 'dpdp_users', ['org_id'], unique=False)
    op.create_index(op.f('ix_dpdp_users_phone_hash'), 'dpdp_users', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_dpdp_users_role'), 'dpdp_users', ['role'], unique=False)
    op.drop_constraint(op.f('dpdp_users_ibfk_1'), 'dpdp_users', type_='foreignkey')
    op.create_foreign_key(None, 'dpdp_users', 'dpdp_orgs', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dpdp_users', type_='foreignkey')
    op.create_foreign_key(op.f('dpdp_users_ibfk_1'), 'dpdp_users', 'dpdp_orgs', ['org_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_dpdp_users_role'), table_name='dpdp_users')
    op.drop_index(op.f('ix_dpdp_users_phone_hash'), table_name='dpdp_users')
    op.drop_index(op.f('ix_dpdp_users_org_id'), table_name='dpdp_users')
    op.drop_index(op.f('ix_dpdp_users_name_hash'), table_name='dpdp_users')
    op.drop_index(op.f('ix_dpdp_users_is_active'), table_name='dpdp_users')
    op.drop_index(op.f('ix_dpdp_users_id'), table_name='dpdp_users')
    op.drop_index(op.f('ix_dpdp_users_email_hash'), table_name='dpdp_users')
    op.drop_index('idx_dpdp_users_email_hash', table_name='dpdp_users')
    op.create_index(op.f('idx_dpdp_users_email_hash'), 'dpdp_users', ['email_hash'], unique=True)
    op.create_index(op.f('idx_dpdp_users_phone_hash'), 'dpdp_users', ['phone_hash'], unique=False)
    op.create_index(op.f('idx_dpdp_users_name_hash'), 'dpdp_users', ['name_hash'], unique=False)
    op.alter_column('dpdp_users', 'is_active',
               existing_type=sa.String(length=1),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('dpdp_users', 'email_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('dpdp_users', 'email',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('dpdp_users', 'name_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('dpdp_users', 'name',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_dpdp_orgs_status'), table_name='dpdp_orgs')
    op.drop_index(op.f('ix_dpdp_orgs_short_code'), table_name='dpdp_orgs')
    op.drop_index(op.f('ix_dpdp_orgs_name'), table_name='dpdp_orgs')
    op.drop_index(op.f('ix_dpdp_orgs_id'), table_name='dpdp_orgs')
    op.drop_index(op.f('ix_dpdp_orgs_dpo_email_hash'), table_name='dpdp_orgs')
    op.drop_index(op.f('ix_dpdp_orgs_dpdp_reg_id'), table_name='dpdp_orgs')
    op.drop_index('idx_dpdp_orgs_name', table_name='dpdp_orgs')
    op.create_index(op.f('idx_dpdp_orgs_name'), 'dpdp_orgs', ['name'], unique=True)
    op.create_index(op.f('idx_dpdp_orgs_short_code'), 'dpdp_orgs', ['short_code'], unique=True)
    op.create_index(op.f('idx_dpdp_orgs_dpo_email_hash'), 'dpdp_orgs', ['dpo_email_hash'], unique=False)
    op.create_index(op.f('idx_dpdp_orgs_dpdp_reg_id'), 'dpdp_orgs', ['dpdp_reg_id'], unique=False)
    op.drop_index(op.f('ix_dpdp_nominations_user_id'), table_name='dpdp_nominations')
    op.drop_index(op.f('ix_dpdp_nominations_nominee_phone_hash'), table_name='dpdp_nominations')
    op.drop_index(op.f('ix_dpdp_nominations_nominee_email_hash'), table_name='dpdp_nominations')
    op.drop_index(op.f('ix_dpdp_nominations_is_active'), table_name='dpdp_nominations')
    op.drop_index(op.f('ix_dpdp_nominations_id'), table_name='dpdp_nominations')
    op.alter_column('dpdp_nominations', 'is_active',
               existing_type=sa.String(length=1),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('dpdp_nominations', 'nominee_email_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint('uq_form_id_version', 'dpdp_form_versions', type_='unique')
    op.drop_index(op.f('ix_dpdp_form_versions_status'), table_name='dpdp_form_versions')
    op.drop_index(op.f('ix_dpdp_form_versions_id'), table_name='dpdp_form_versions')
    op.drop_index(op.f('ix_dpdp_form_versions_form_id'), table_name='dpdp_form_versions')
    op.create_index(op.f('uq_dpdp_form_versions_form_version'), 'dpdp_form_versions', ['form_id', 'version'], unique=True)
    op.alter_column('dpdp_form_versions', 'expiry_days',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('dpdp_form_versions', 'retention_days',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_constraint('uq_user_form_version', 'dpdp_consents', type_='unique')
    op.drop_index(op.f('ix_dpdp_consents_user_id'), table_name='dpdp_consents')
    op.drop_index(op.f('ix_dpdp_consents_status'), table_name='dpdp_consents')
    op.drop_index(op.f('ix_dpdp_consents_id'), table_name='dpdp_consents')
    op.drop_index(op.f('ix_dpdp_consents_form_id'), table_name='dpdp_consents')
    op.drop_index(op.f('ix_dpdp_consents_expires_at'), table_name='dpdp_consents')
    op.create_index(op.f('idx_dpdp_consents_user_form'), 'dpdp_consents', ['user_id', 'form_id'], unique=False)
    op.create_index(op.f('idx_dpdp_consents_granted_at'), 'dpdp_consents', ['granted_at'], unique=False)
    op.drop_index(op.f('ix_dpdp_consent_forms_status'), table_name='dpdp_consent_forms')
    op.drop_index(op.f('ix_dpdp_consent_forms_org_id'), table_name='dpdp_consent_forms')
    op.drop_index(op.f('ix_dpdp_consent_forms_name'), table_name='dpdp_consent_forms')
    op.drop_index(op.f('ix_dpdp_consent_forms_id'), table_name='dpdp_consent_forms')
    op.drop_index(op.f('ix_dpdp_consent_forms_code'), table_name='dpdp_consent_forms')
    op.drop_index('idx_dpdp_consent_forms_code', table_name='dpdp_consent_forms')
    op.create_index(op.f('idx_dpdp_consent_forms_code'), 'dpdp_consent_forms', ['code'], unique=True)
    op.alter_column('dpdp_consent_forms', 'expiry_days',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('dpdp_consent_forms', 'retention_days',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('dpdp_consent_forms', 'legal_basis',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_index(op.f('ix_dpdp_audit_log_ts'), table_name='dpdp_audit_log')
    op.drop_index(op.f('ix_dpdp_audit_log_target'), table_name='dpdp_audit_log')
    op.drop_index(op.f('ix_dpdp_audit_log_org_id'), table_name='dpdp_audit_log')
    op.drop_index(op.f('ix_dpdp_audit_log_id'), table_name='dpdp_audit_log')
    op.drop_index(op.f('ix_dpdp_audit_log_actor_type'), table_name='dpdp_audit_log')
    op.drop_index(op.f('ix_dpdp_audit_log_actor'), table_name='dpdp_audit_log')
    op.drop_index(op.f('ix_dpdp_audit_log_action'), table_name='dpdp_audit_log')
    op.create_index(op.f('idx_dpdp_audit_log_target'), 'dpdp_audit_log', ['target'], unique=False)
    op.create_index(op.f('idx_dpdp_audit_log_actor_type'), 'dpdp_audit_log', ['actor_type'], unique=False)
    op.drop_index(op.f('ix_dpdp_async_jobs_status'), table_name='dpdp_async_jobs')
    op.drop_index(op.f('ix_dpdp_async_jobs_org_id'), table_name='dpdp_async_jobs')
    op.drop_index(op.f('ix_dpdp_async_jobs_job_type'), table_name='dpdp_async_jobs')
    op.drop_index(op.f('ix_dpdp_async_jobs_id'), table_name='dpdp_async_jobs')
    op.drop_index(op.f('ix_dpdp_async_jobs_form_id'), table_name='dpdp_async_jobs')
    op.drop_index('idx_dpdp_async_jobs_type', table_name='dpdp_async_jobs')
    op.create_index(op.f('idx_dpdp_async_jobs_job_type'), 'dpdp_async_jobs', ['job_type'], unique=False)
    op.create_index(op.f('idx_dpdp_async_jobs_form_id'), 'dpdp_async_jobs', ['form_id'], unique=False)
    op.alter_column('dpdp_async_jobs', 'failed',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('dpdp_async_jobs', 'processed',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('dpdp_async_jobs', 'total',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
